import type { Category, SubCategory, Brand, Product } from "./types";

export const categories: Category[] = [
  { id: "1", categoryName: "CPU", iconImg: "🔲" },
  { id: "2", categoryName: "GPU", iconImg: "🎮" },
  { id: "3", categoryName: "RAM", iconImg: "💾" },
  { id: "4", categoryName: "Mainboard", iconImg: "⚡" },
  { id: "5", categoryName: "Storage", iconImg: "💿" },
  { id: "6", categoryName: "PSU", iconImg: "🔋" },
  { id: "7", categoryName: "Case", iconImg: "📦" },
  { id: "8", categoryName: "Cooling", iconImg: "❄️" },
];

export const subCategories: SubCategory[] = [
  {
    id: "1",
    categoryId: "1",
    subCategoryName: "Intel CPU",
    subCategoryImg: "/test.png",
    description: "Intel Processors",
  },
  {
    id: "2",
    categoryId: "1",
    subCategoryName: "AMD CPU",
    subCategoryImg: "/test.png",
    description: "AMD Processors",
  },
  {
    id: "3",
    categoryId: "2",
    subCategoryName: "NVIDIA GPU",
    subCategoryImg: "/test.png",
    description: "NVIDIA Graphics Cards",
  },
  {
    id: "4",
    categoryId: "2",
    subCategoryName: "AMD GPU",
    subCategoryImg: "/test.png",
    description: "AMD Graphics Cards",
  },
  {
    id: "5",
    categoryId: "3",
    subCategoryName: "DDR4 RAM",
    subCategoryImg: "/test.png",
    description: "DDR4 Memory",
  },
  {
    id: "6",
    categoryId: "3",
    subCategoryName: "DDR5 RAM",
    subCategoryImg: "/test.png",
    description: "DDR5 Memory",
  },
];

export const brands: Brand[] = [
  { id: "1", brandName: "Intel", categoryId: "1" },
  { id: "2", brandName: "AMD", categoryId: "1" },
  { id: "3", brandName: "NVIDIA", categoryId: "2" },
  { id: "4", brandName: "ASUS", categoryId: "4" },
  { id: "5", brandName: "MSI", categoryId: "4" },
  { id: "6", brandName: "Gigabyte", categoryId: "4" },
  { id: "7", brandName: "Corsair", categoryId: "3" },
  { id: "8", brandName: "G.Skill", categoryId: "3" },
];

export const products: Product[] = [
  {
    id: "1",
    subCategoryId: "1",
    productName: "Intel Core i9-14900K",
    price: 15990000,
    stockQuantity: 25,
    createdAt: "2024-01-15T00:00:00Z",
    description:
      "CPU Intel Core i9 thế hệ 14, 24 nhân 32 luồng, tốc độ tối đa 6.0GHz",
    thumbnail: "/test.png",
    status: "active",
    brandId: "1",
    brandName: "Intel",
    subCategoryName: "Intel CPU",
    warrantyPeriod: 36,
  },
  {
    id: "2",
    subCategoryId: "2",
    productName: "AMD Ryzen 9 7950X",
    price: 14990000,
    stockQuantity: 30,
    createdAt: "2024-01-16T00:00:00Z",
    description:
      "CPU AMD Ryzen 9 7950X, 16 nhân 32 luồng, tốc độ tối đa 5.7GHz",
    thumbnail: "/test.png",
    status: "active",
    brandId: "2",
    brandName: "AMD",
    subCategoryName: "AMD CPU",
    warrantyPeriod: 36,
  },
  {
    id: "3",
    subCategoryId: "3",
    productName: "NVIDIA RTX 4090",
    price: 45990000,
    stockQuantity: 15,
    createdAt: "2024-01-17T00:00:00Z",
    description: "Card đồ họa NVIDIA GeForce RTX 4090, 24GB GDDR6X",
    thumbnail: "/test.png",
    status: "active",
    brandId: "3",
    brandName: "NVIDIA",
    subCategoryName: "NVIDIA GPU",
    warrantyPeriod: 24,
  },
  {
    id: "4",
    subCategoryId: "3",
    productName: "NVIDIA RTX 4080",
    price: 32990000,
    stockQuantity: 20,
    createdAt: "2024-01-18T00:00:00Z",
    description: "Card đồ họa NVIDIA GeForce RTX 4080, 16GB GDDR6X",
    thumbnail: "/test.png",
    status: "active",
    brandId: "3",
    brandName: "NVIDIA",
    subCategoryName: "NVIDIA GPU",
    warrantyPeriod: 24,
  },
  {
    id: "5",
    subCategoryId: "5",
    productName: "Corsair Vengeance DDR4 32GB",
    price: 2990000,
    stockQuantity: 50,
    createdAt: "2024-01-19T00:00:00Z",
    description: "RAM Corsair Vengeance DDR4 32GB (2x16GB) 3200MHz",
    thumbnail: "/test.png",
    status: "active",
    brandId: "7",
    brandName: "Corsair",
    subCategoryName: "DDR4 RAM",
    warrantyPeriod: 12,
  },
  {
    id: "6",
    subCategoryId: "6",
    productName: "G.Skill Trident Z5 DDR5 32GB",
    price: 4990000,
    stockQuantity: 40,
    createdAt: "2024-01-20T00:00:00Z",
    description: "RAM G.Skill Trident Z5 DDR5 32GB (2x16GB) 6000MHz",
    thumbnail: "/test.png",
    status: "active",
    brandId: "8",
    brandName: "G.Skill",
    subCategoryName: "DDR5 RAM",
    warrantyPeriod: 12,
  },
];

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("vi-VN", {
    style: "currency",
    currency: "VND",
  }).format(price);
}
